<html><head><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/image.min.css"></head><body><div class="container"><div class="row"><div class="col-md-10 col-md-offset-1 ui image"><p class="lead"><p>I did not mention this in the lecture but error handling with fetch is a bit different than with something like Axios or jQuery. If there is an http error, it will not fire off .catch automatically. You have to check the response and throw an error yourself. Here is an example....</p><p><br></p><pre class="prettyprint linenums">fetch('https://devcamper.io/api/v1/bootcamps/34343')<br>&nbsp;&nbsp;.then(res&nbsp;=&gt;&nbsp;res.json())<br>&nbsp;&nbsp;.then(res&nbsp;=&gt;&nbsp;{<br>    if (!res.ok) {<br>       throw new Error(res.error);<br>    }<br>    return res;<br>  })<br>&nbsp;&nbsp;.catch(err&nbsp;=&gt;&nbsp;console.log(err));<br></pre><p>I would suggest creating a separate function for error handling</p><pre class="prettyprint linenums">function&nbsp;handleErrors(res)&nbsp;{<br>&nbsp;&nbsp;if&nbsp;(!res.ok)&nbsp;throw&nbsp;new&nbsp;Error(res.error);<br>&nbsp;&nbsp;return&nbsp;res;<br>}<br>fetch('https://devcamper.io/api/v1/bootcamps/34343')<br>&nbsp;&nbsp;.then(res&nbsp;=&gt;&nbsp;res.json())<br>&nbsp;&nbsp;.then(handleErrors)<br>&nbsp;&nbsp;.then(res&nbsp;=&gt;&nbsp;console.log(res.data))<br>&nbsp;&nbsp;.catch(err&nbsp;=&gt;&nbsp;console.log(err));<br></pre></p></div></div></div></body></html>